// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var RepoItem$ReactTemplate = require("./RepoItem.bs.js");

var component = ReasonReact.reducerComponent("App");

var dummyRepo = /* record */[
  /* full_name */"jsdf/reason-react-hacker-news",
  /* stargazers_count */27,
  /* html_url */"https://github.com/jsdf/reason-react-hacker-news"
];

function make() {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (self) {
              var match = self[/* state */1][/* repoData */0];
              var repoItem = match ? ReasonReact.element(/* None */0, /* None */0, RepoItem$ReactTemplate.make(match[0], /* array */[])) : "Loading";
              return React.createElement("div", undefined, React.createElement("h1", undefined, "Reason Projects"), repoItem);
            }),
          /* initialState */(function () {
              return /* record */[/* repoData : Some */[dummyRepo]];
            }),
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */(function (_, _$1) {
              return /* NoUpdate */0;
            }),
          /* subscriptions */component[/* subscriptions */13],
          /* jsElementWrapped */component[/* jsElementWrapped */14]
        ];
}

exports.component = component;
exports.dummyRepo = dummyRepo;
exports.make = make;
/* component Not a pure module */
